### ISSUE TITLE
DRY (DONT REPEAT YOURSELF)

### ISSUE THREAD

**Issue by Sherlockboy** [Orifjon-github/laravel-teach#3]
https://github.com/Orifjon-github/laravel-task/blob/main/app/Http/Controllers/ApplicationController.php

Yuqoridagi fileda ushbu code qaytarilgan:
```auth()->user()->applications()->latest()->first()```

**Comment by Orifjon-github** [comment]
![image](https://user-images.githubusercontent.com/84227410/213258737-122eaa31-ee39-45de-a281-cd33a9cfebff.png)

Kod takrorlanishi to'g'irlandi va qo'shimcha funksiyada oshiqcha bo'lgan if olib tashlandi
