### ISSUE TITLE
Route grouping

### ISSUE THREAD

**Issue by Sherlockboy** [Orifjon-github/laravel-teach#4]
web.php file dagi route larni gruppalash imkoniyati bor, iloji boricha guruppalab code ni ixchamlashtirsangiz yaxshi.

**Comment by Orifjon-github** [comment]
Role:manager middleware bitta gruppa qilindi. 
Profile routelari Alohida auth middleware da turgan ekan, u ham Umumiy auth middleware guruhiga qo'shildi.
Qo'ldan kelgancha web.php routelari ixchamlashtirildi
